name: Update
on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm i
      - run: node dist/index.js
      - name: Commit & Push
        uses: actions-x/commit@v2
        with:
          email: noreply@charlie.fish
          name: GitHub Actions
          branch: main
          files: data
          message: 'Updating data'
